export const BRAZILIAN_STATES = {
  acre: 'Acre',
  alagoas: 'Alagoas',
  amapa: 'Amapá',
  amazonas: 'Amazonas',
  bahia: 'Bahia',
  ceara: 'Ceará',
  'distrito-federal': 'Distrito Federal',
  'espirito-santo': 'Espírito Santo',
  goias: 'Goiás',
  maranhao: 'Maranhão',
  'mato-grosso': 'Mato Grosso',
  'mato-grosso-do-sul': 'Mato Grosso do Sul',
  'minas-gerais': 'Minas Gerais',
  para: 'Pará',
  paraiba: 'Paraíba',
  parana: 'Paraná',
  pernambuco: 'Pernambuco',
  piaui: 'Piauí',
  'rio-de-janeiro': 'Rio de Janeiro',
  'rio-grande-do-norte': 'Rio Grande do Norte',
  'rio-grande-do-sul': 'Rio Grande do Sul',
  rondonia: 'Rondônia',
  roraima: 'Roraima',
  'santa-catarina': 'Santa Catarina',
  'sao-paulo': 'São Paulo',
  sergipe: 'Sergipe',
  tocantins: 'Tocantins',
}

export const SELECT_BRAZILIAN_STATES = Object.entries(BRAZILIAN_STATES).map(
  ([value, label]) => ({ label, value }),
)
